// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "provider": string;
      "autoCreateNote": boolean;
      "showDetailedProgress": boolean;
      "temperature": number;
      "maxTokens": number;
      "charts.timeline": boolean;
      "charts.topic": boolean;
      "charts.method": boolean;
      "charts.citation": boolean;
      "charts.keyword": boolean;
      "openai.apiKey": string;
      "openai.baseURL": string;
      "openai.model": string;
      "openai.timeout": number;
      "openai.maxRetries": number;
      "anthropic.apiKey": string;
      "anthropic.baseURL": string;
      "anthropic.model": string;
      "deepseek.apiKey": string;
      "deepseek.baseURL": string;
      "deepseek.model": string;
      "aliyun.apiKey": string;
      "aliyun.baseURL": string;
      "aliyun.model": string;
      "bytedance.apiKey": string;
      "bytedance.baseURL": string;
      "bytedance.model": string;
      "custom.apiKey": string;
      "custom.baseURL": string;
      "custom.model": string;
    };
  }
}
